name: "Rectorize"
on: 
  workflow_dispatch:
    inputs:
      gitUrl:
        description: "Git URL"
        required: true
      phpVersion:
        description: "Target PHP version"
        required: false
        default: "7.4"
      processOptions:
        description: "Command line options"
        required: true
        default: "src/"

jobs:
  rector:
    name: "Rector"
    runs-on: ubuntu-latest
    steps:
      - name: "Set default PHP version"
        run: "sudo update-alternatives --set php /usr/bin/php8.0"

      - name: "Checkout code"
        uses: "actions/checkout@v2"

      - name: "Clone project and install dependencies"
        run: |
          git clone "${{ github.event.inputs.gitUrl }}" build/
          cd build/
          composer update --no-interaction --ignore-platform-reqs --prefer-dist
          composer require --no-interaction --ignore-platform-reqs --no-script symfony/polyfill-php80
          composer require --no-interaction --ignore-platform-reqs --no-script --dev rector/rector-prefixed

      - name: "Set target PHP version to 7.3"
        if: "github.event.inputs.phpVersion == '7.3'"
        run: |
          sed -i -e 's#//PHP73 ##' rector.php
          cd build/
          composer require --no-interaction --ignore-platform-reqs --no-script symfony/polyfill-php74

      - name: "Set target PHP version to 7.2"
        if: "github.event.inputs.phpVersion == '7.2'"
        run: |
          sed -i -e 's#//PHP72 ##' rector.php
          cd build/
          composer require --no-interaction --ignore-platform-reqs --no-script symfony/polyfill-php74 symfony/polyfill-php73

      - name: "Set target PHP version to 7.1"
        if: "github.event.inputs.phpVersion == '7.1'"
        run: |
          sed -i -e 's#//PHP71 ##' rector.php
          cd build/
          composer require --no-interaction --ignore-platform-reqs --no-script symfony/polyfill-php74 symfony/polyfill-php73 symfony/polyfill-php72

      - name: "Set target PHP version to 7.0"
        if: "github.event.inputs.phpVersion == '7.0'"
        run: |
          sed -i -e 's#//PHP70 ##' rector.php
          cd build/
          composer require --no-interaction --ignore-platform-reqs --no-script symfony/polyfill-php74 symfony/polyfill-php73 symfony/polyfill-php72 symfony/polyfill-php71

      - name: "Set target PHP version to 5.6"
        if: "github.event.inputs.phpVersion == '5.6'"
        run: |
          sed -i -e 's#//PHP56 ##' rector.php
          cd build/
          composer require --no-interaction --ignore-platform-reqs --no-script symfony/polyfill-php74 symfony/polyfill-php73 symfony/polyfill-php72 symfony/polyfill-php71 symfony/polyfill-php70

      - name: "Rectify project"
        run: |
          cd build/
          vendor/bin/rector process --config=../rector.php ${{ github.event.inputs.processOptions }}
          tar -cf build.tar .

      - name: "Upload rectified source code"
        uses: "actions/upload-artifact@v2"
        with:
          name: "results"
          path: "build/build.tar"
          retention-days: 1
